// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/getByAuthToken': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/getByAuthToken').default>>>>
    }
    '/api/auth/login': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login').default>>>>
    }
    '/api/auth/logout': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout').default>>>>
    }
    '/api/auth/register': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register').default>>>>
    }
    '/api/comment/addComment': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comment/addComment').default>>>>
    }
    '/api/comment/deleteComment': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comment/deleteComment').default>>>>
    }
    '/api/comment/getComments': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comment/getComments').default>>>>
    }
    '/api/like/addLike': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/like/addLike').default>>>>
    }
    '/api/like/deleteLike': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/like/deleteLike').default>>>>
    }
    '/api/like/getLikes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/like/getLikes').default>>>>
    }
    '/api/players': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/players').default>>>>
    }
    '/api/subscribe': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subscribe').default>>>>
    }
    '/api/teams': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/teams').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_mdc/highlight': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/mdc/dist/runtime/highlighter/event-handler').default>>>>
    }
    '/api/_content/query/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query-qid-params').default>>>>
    }
    '/api/_content/query/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query-qid').default>>>>
    }
    '/api/_content/query': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/cache.1735430513628.json': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/cache').default>>>>
    }
    '/api/_content/navigation/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation-qid-params').default>>>>
    }
    '/api/_content/navigation/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation-qid').default>>>>
    }
    '/api/_content/navigation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
  }
}
export {}